/* @generated by common/sync.mjs — do not edit this copy.
 * @source  sheet/collapse.mjs
 * @version 1.3.0
 * @sha256  60f1f47899a22e98
 * @vars    PREFIX=pfsum-
 *
 * Edit common/sheet/collapse.mjs and re-run `node common/sync.mjs`.
 */

/**
 * Collapsible item-sheet sections.
 *
 * A section appended to the Advanced tab is dead space on the majority of items that don't
 * configure it. This turns a section's existing `h3.form-header` into the toggle: the section's
 * own topical icon doubles as the disclosure control - full strength when open, dimmed when
 * closed - so an expanded header looks exactly as it did before. An optional badge on the right
 * keeps a summary visible while collapsed.
 *
 * Expanded state lives in memory for as long as the sheet is open, keyed by `appId`. Reopening
 * the item re-applies the default, which is "open only if this section is actually configured".
 * Nothing is written to the document.
 */

/** @type {Map<string, boolean>} `${appId}:${key}` -> expanded */
const memo = new Map();

/**
 * Make a section collapsible by its header.
 *
 * @param {Application} app                    The sheet the section was injected into.
 * @param {JQuery|HTMLElement} section         Section root.
 * @param {object} opts
 * @param {string} opts.key                    Distinguishes sections sharing one sheet.
 * @param {string} [opts.marker]               Shorthand: derives `header`/`body` as
 *                                             `.<marker>-header` / `.<marker>-body`.
 * @param {string} [opts.header]               Selector for the header inside `section`.
 * @param {string} [opts.body]                 Selector for the collapsible body inside `section`.
 * @param {boolean} [opts.configured]          Default-open when true.
 * @param {number|string|null} [opts.badge]    Shown at the header's right edge. `null` omits the
 *                                             element entirely; a falsy value keeps it in the DOM
 *                                             but hidden, so the section's own code can update it
 *                                             in place.
 * @param {string} [opts.title]                Header tooltip.
 * @param {string|false} [opts.sortKey]        Position among the tab's other sections; defaults
 *                                             to the header text. `false` keeps the section
 *                                             wherever its module put it.
 */
export function makeCollapsible(
  app,
  section,
  { key, marker, header, body, configured = false, badge = null, title = "Click to expand / collapse", sortKey } = {}
) {
  const root = section instanceof jQuery ? section[0] : section;
  const headerEl = root?.querySelector(header ?? `.${marker}-header`);
  const bodyEl = root?.querySelector(body ?? `.${marker}-body`);
  if (!headerEl || !bodyEl) return;

  // Read before the badge is appended, or its text becomes part of the key.
  if (sortKey !== false) placeSorted(root, sortKey ?? headerEl.textContent.replace(/\s+/g, " ").trim());

  root.classList.add("pfsum-collapsible");
  headerEl.classList.add("pfsum-collapse-header");
  headerEl.setAttribute("title", title);

  if (badge !== null) {
    const el = document.createElement("span");
    el.className = "pfsum-collapse-badge";
    el.textContent = String(badge);
    if (!badge) el.style.display = "none";
    headerEl.append(el);
  }

  const memoKey = `${app.appId}:${key}`;
  let expanded = memo.get(memoKey) ?? !!configured;

  const apply = () => {
    root.classList.toggle("pfsum-collapsed", !expanded);
    bodyEl.style.display = expanded ? "" : "none";
  };
  apply();

  headerEl.addEventListener("click", (event) => {
    // Headers can carry their own controls; let those win.
    if (event.target.closest("a, button, input, select")) return;
    event.preventDefault();
    // The header click is the collapse control and nothing else's business. From
    // pf1-improved-energy-drain, whose sections sit on container sheets too.
    event.stopPropagation();
    expanded = !expanded;
    memo.set(memoKey, expanded);
    apply();
  });
}

/**
 * Tabs whose sections are free-placed. Elsewhere (Details, Action) each section is anchored to
 * the field it belongs beside, so order is left to its module.
 */
const SORTED_TABS = '.tab[data-tab="advanced"], .tab[data-tab="misc"]';

/**
 * Shared across every module's copy, so it cannot carry `pfsum-`: the sections being
 * ordered come from different modules.
 */
const SORT_ATTR = "data-sheet-sort";

/**
 * Move a section into sorted position among the tab's other kit sections.
 *
 * Every section places itself on arrival, so the result is the same whichever module's async
 * render finishes first. The first to arrive anchors the block directly below Script Calls.
 */
function placeSorted(root, key) {
  const tab = root.closest(SORTED_TABS);
  if (!tab) return;
  const tabBody = tab.querySelector(":scope > .flexcol") ?? tab;
  // Nested inside another element: that host owns the placement.
  if (root.parentElement !== tabBody && root.parentElement !== tab) return;

  root.setAttribute(SORT_ATTR, key);
  const peers = [...tabBody.querySelectorAll(`:scope > [${SORT_ATTR}]`)].filter((el) => el !== root);
  const next = peers.find((el) => el.getAttribute(SORT_ATTR).localeCompare(key, undefined, { sensitivity: "base" }) > 0);
  if (next) return void next.before(root);
  if (peers.length) return void peers.at(-1).after(root);

  const scriptCalls = tabBody.querySelector(":scope > .script-calls");
  if (scriptCalls) scriptCalls.after(root);
  else if (root.parentElement !== tabBody) tabBody.append(root);
}

/** Update a section's badge in place. */
export function setBadge(section, value) {
  const root = section instanceof jQuery ? section[0] : section;
  const el = root?.querySelector(".pfsum-collapse-badge");
  if (!el) return;
  el.textContent = String(value ?? "");
  el.style.display = value ? "" : "none";
}

/** Drop a sheet's remembered state when it closes. */
function forget(app) {
  const prefix = `${app.appId}:`;
  for (const k of memo.keys()) if (k.startsWith(prefix)) memo.delete(k);
}

// All of them: a hook that never fires costs nothing, and which of these a given host uses
// has been the main way the copies of this file drifted. `_Container` came from
// pf1-improved-energy-drain, the only copy that had it.
Hooks.on("closeItemSheetPF", forget);
Hooks.on("closeItemSheetPF_Container", forget);
Hooks.on("closeItemActionSheet", forget);
Hooks.on("closeItemSheet", forget);
