/* @generated by common/sync.mjs — do not edit this copy.
 * @source  sheet/field-bind.mjs
 * @version 1.2.0
 * @sha256  3366023e55309c29
 * @vars    PREFIX=pfsum-
 *
 * Edit common/sheet/field-bind.mjs and re-run `node common/sync.mjs`.
 */

/**
 * Declarative binding between a section's inputs and a document's flag payload.
 *
 * Every injected config section repeats the same three things per field: seed the input from
 * stored config, persist on change, and stop the event so a host sheet with `submitOnChange`
 * doesn't resubmit underneath. Hand-written that is ~8 lines a field; buff-delivery carries
 * about twenty of them.
 *
 * Fields are addressed by a `data-field` attribute, so the template names each control once
 * and the binding map says what it means.
 */

/** Read the value out of a control according to its declared type. */
function readControl(el, type) {
  switch (type) {
    case "checkbox":
      return el.checked;
    case "number": {
      const n = Number(el.value);
      return Number.isFinite(n) ? n : 0;
    }
    case "set": {
      // A group of checkboxes sharing one field name -> array of the checked values.
      return null; // handled by bindFields, which sees the whole group
    }
    default:
      return String(el.value ?? "").trim();
  }
}

/** Write a stored value into a control. */
function writeControl(el, type, value) {
  if (type === "checkbox") el.checked = !!value;
  else el.value = value ?? "";
}

/**
 * Bind a section's controls to a flag payload.
 *
 * @param {HTMLElement|JQuery} section  Root to search for `[data-field]` controls.
 * @param {object} opts
 * @param {Document} opts.doc           Document to persist onto.
 * @param {string} opts.base            Flag path prefix, e.g. `flags.my-module.config`.
 * @param {object} opts.values          Current config, used to seed the controls.
 * @param {object} opts.fields          `{ fieldName: { type, toggles?, onChange? } }` where
 *                                      `type` is "text" | "number" | "checkbox" | "set",
 *                                      `toggles` is a class put on the section while truthy,
 *                                      and `onChange` runs after a successful save.
 * @returns {{refresh: () => void}}
 */
export function bindFields(section, { doc, base, values = {}, fields = {} }) {
  const root = section instanceof jQuery ? section[0] : section;
  if (!root) return { refresh: () => {} };

  // Persist without re-rendering: the section owns its own DOM state, and a render here
  // would fight the host sheet mid-interaction.
  const save = (name, value) => doc.update({ [`${base}.${name}`]: value }, { render: false });

  const applyToggle = (name, spec, value) => {
    if (spec.toggles) root.classList.toggle(spec.toggles, !!value);
  };

  for (const [name, spec] of Object.entries(fields)) {
    const controls = [...root.querySelectorAll(`[data-field="${name}"]`)];
    if (!controls.length) continue;

    const type = spec.type ?? "text";

    if (type === "set") {
      const current = new Set(values[name] ?? []);
      for (const el of controls) el.checked = current.has(el.value);

      for (const el of controls) {
        el.addEventListener("change", async (event) => {
          event.stopPropagation();
          const chosen = controls.filter((c) => c.checked).map((c) => c.value);
          await save(name, chosen);
          spec.onChange?.(chosen, root);
        });
      }
      continue;
    }

    for (const el of controls) writeControl(el, type, values[name]);
    applyToggle(name, spec, values[name]);

    for (const el of controls) {
      el.addEventListener("change", async (event) => {
        event.stopPropagation();
        const value = readControl(el, type);
        applyToggle(name, spec, value);
        await save(name, value);
        spec.onChange?.(value, root);
      });
    }
  }

  return {
    /** Re-seed every control from the document's current stored values. */
    refresh() {
      const stored = foundry.utils.getProperty(doc, base) ?? {};
      for (const [name, spec] of Object.entries(fields)) {
        const controls = [...root.querySelectorAll(`[data-field="${name}"]`)];
        const type = spec.type ?? "text";
        if (type === "set") {
          const current = new Set(stored[name] ?? []);
          for (const el of controls) el.checked = current.has(el.value);
        } else {
          for (const el of controls) writeControl(el, type, stored[name]);
          applyToggle(name, spec, stored[name]);
        }
      }
    },
  };
}
