/* @generated by common/sync.mjs — do not edit this copy.
 * @source  sheet/formula-preview.mjs
 * @version 1.2.0
 * @sha256  14c50559b97613f8
 * @vars    PREFIX=pfsum-
 *
 * Edit common/sheet/formula-preview.mjs and re-run `node common/sync.mjs`.
 */

/**
 * Live formula preview for a sheet input, plus a hover tooltip breaking the formula down.
 *
 * A `= value` readout updates per keystroke beside any input holding a PF1 formula, and
 * hovering it shows the base formula, its resolved form, and each `@variable`'s current value.
 *
 * Self-contained rather than coupled to Little Helper's equivalent: LH's resolver isn't
 * exported and only runs at render time.
 */

/**
 * Attach a preview to one input.
 *
 * @param {HTMLInputElement} input      The formula field.
 * @param {object} rollData             Roll data to resolve against.
 * @param {object} [opts]
 * @param {HTMLElement} [opts.target]   Where to write the readout. Defaults to a
 *                                      `.pfsum-preview` sibling, created if absent.
 * @param {() => boolean} [opts.active] Return false to blank the readout - for a field whose
 *                                      row is currently toggled off.
 */
export function attachFormulaPreview(input, rollData, { target, active } = {}) {
  if (!input) return;

  let readout = target ?? input.parentElement?.querySelector(".pfsum-preview");
  if (!readout) {
    readout = document.createElement("span");
    readout.className = "pfsum-preview";
    input.after(readout);
  }

  const refresh = () => {
    if (active && !active()) {
      readout.textContent = "";
      return;
    }
    const formula = String(input.value ?? "").trim();
    if (!/@/.test(formula)) {
      readout.textContent = "";
      return;
    }
    let out = "?";
    try {
      const value = Roll.safeEval(Roll.replaceFormulaData(formula, rollData, { missing: 0 }));
      if (Number.isFinite(value)) out = String(value);
    } catch (_) {
      /* an in-progress formula is not an error worth reporting */
    }
    readout.textContent = `= ${out}`;
  };

  refresh();
  input.addEventListener("input", refresh);
  readout.addEventListener("pointerenter", () => showTooltip(readout, input, rollData));
  readout.addEventListener("pointerleave", () => game.tooltip.deactivate());

  return refresh;
}

/** Base formula, resolved form, and each `@variable`'s value. */
function showTooltip(anchor, input, rollData) {
  const formula = String(input.value ?? "").trim();
  if (!formula) return;

  const node = (tag, text, cls) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  };

  const content = document.createElement("div");
  content.append(node("h4", "Formula"), node("div", formula, "pfsum-tt-formula"));

  const resolved = Roll.replaceFormulaData(formula, rollData, { missing: 0 });
  if (resolved !== formula) {
    content.append(node("h4", "Resolved"), node("div", resolved, "pfsum-tt-formula"));
  }

  const vars = [...new Set((formula.match(/@[\w.-]+/g) ?? []).map((s) => s.slice(1)))];
  if (vars.length) {
    const list = node("ul", null, "pfsum-tt-vars");
    for (const path of vars) {
      const value = foundry.utils.getProperty(rollData, path);
      list.append(node("li", `@${path} = ${value === undefined ? "—" : value}`));
    }
    content.append(node("h4", "Variables"), list);
  }

  game.tooltip.activate(anchor, { html: content, direction: "UP", cssClass: "pfsum-formula-tooltip" });
}
